# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'difficult.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QBrush, QPalette


class Ui_Complexity(object):
    def setupUi(self, Complexity):
        Complexity.setObjectName("Complexity")
        Complexity.setFixedSize(182, 148)
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap(r"FASTqt\test1\110+.jpg")))
        Complexity.setPalette(palette)
        self.radioButton = QtWidgets.QRadioButton(Complexity)
        self.radioButton.setGeometry(QtCore.QRect(0, 40, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Complexity)
        self.radioButton_2.setGeometry(QtCore.QRect(0, 60, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Complexity)
        self.radioButton_3.setGeometry(QtCore.QRect(0, 80, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.label = QtWidgets.QLabel(Complexity)
        self.label.setGeometry(QtCore.QRect(30, 10, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Coiny 2.0")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.radioButton_4 = QtWidgets.QRadioButton(Complexity)
        self.radioButton_4.setGeometry(QtCore.QRect(0, 100, 181, 17))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "color: rgb(203, 15, 15);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_2 = QtWidgets.QLabel(Complexity)
        self.label_2.setGeometry(QtCore.QRect(0, 120, 180, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Complexity)
        QtCore.QMetaObject.connectSlotsByName(Complexity)

    def retranslateUi(self, Complexity):
        _translate = QtCore.QCoreApplication.translate
        Complexity.setWindowTitle(_translate("Complexity", "complexity"))
        self.radioButton.setText(_translate("Complexity", "легко"))
        self.radioButton_2.setText(_translate("Complexity", "нормально"))
        self.radioButton_3.setText(_translate("Complexity", "сложно"))
        self.label.setText(_translate("Complexity", "Сложность"))
        self.radioButton_4.setText(_translate("Complexity", "олимпиадные задания"))
        self.label_2.setText(_translate("Complexity", ""))
